import Head from 'next/head'
import { useSelector } from 'react-redux'
import Link from 'next/link'
import { Avatar } from 'components'
import styles from 'styles/home.module.scss'

export default function Home() {
  const count = useSelector((state) => state.counter.count)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Avatar />
        <h1 className='title'>
          Go to{' '}
          <Link href='/posts/firstPost'>
            First Post (simple counter)
          </Link>
        </h1>

        <h1 className='title'>
          Go to{' '}
          <Link href='/posts/counter'>
            Counter (redux counter) :
          </Link>
          {' '}{count}
        </h1>

        <h1 className='title'>
          Go to{' '}
          <Link href='/posts/users'>
            Users
          </Link>
        </h1>

        <h1 className='title'>
          Go to{' '}
          <Link href='/posts/usersStaticProps'>
            Users (getStaticProps)
          </Link>
        </h1>
      </main>
    </div>
  )
}
